image: node:10.13.0

stages:
  - init
  - tests
  - output

cache:
  paths:
    - node_modules/

init:
  stage: init
  script:
    - npm install

tests:
  stage: tests
  script:
    # We need to specify the reporter b/c tap defaults to standard TAP output
    # when stdout is not a terminal, which it apparently isn't in the gitlab
    # test runner output.
    - npm test

output:
  stage: output
  script:
    - tail -n 1000 instances/*/logs/*
