# alpine is a much smaller image, and we can use it, so we will use it to
# speed up our build times. (https://hub.docker.com/_/node/)
image: node:8.12.0-alpine

stages:
  - init
  - tests

cache:
  paths:
    - node_modules/

init:
  stage: init
  script:
    - npm install

tests:
  stage: tests
  script:
    # We need to specify the reporter b/c tap defaults to standard TAP output
    # when stdout is not a terminal, which it apparently isn't in the gitlab
    # test runner output.
    - npm test -- --reporter classic
