name: Node CI Workflow
on:
  push:
    branches:
      - dev
  issue_comment:
    inputs:
      workflowBranch:
        description: 'Branch of the reusable workflow. Defaults to main, select dev for testing only.'
        required: false
        default: 'main'
        type: choice
        options:
          - dev
          - main
  workflow_dispatch:
    inputs:
      workflowBranch:
        description: 'Branch of the reusable workflow. Defaults to main, select dev for testing only.'
        required: false
        default: 'main'
jobs:
  echo-inputs:
    name: Repo Workflow Debugging
    runs-on: ubuntu-latest
    steps:
      - name: Check Repo 
    uses: shardeum/github-automation/.github/workflows/reusable-node-ci.yml@dev
    permissions:
      issues: read
      contents: read
  ci:
    if: ${{ github.event.inputs.workflowBranch == 'main' || !github.event.inputs.workflowBranch }}
    uses: shardeum/github-automation/.github/workflows/reusable-node-ci.yml@main
    permissions:
      issues: read
      pull-requests: wread
      contents: read
