name: Node CI Workflow
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
  issue_comment:
    inputs:
      workflowBranch:
        description: 'Branch of the reusable workflow. Defaults to main, select dev for testing only.'
        required: false
        default: 'main'
        type: choice
        options:
          - dev
          - main
  workflow_dispatch:
    inputs:
      workflowBranch:
        description: 'Branch of the reusable workflow. Defaults to main, select dev for testing only.'
        required: false
        default: 'main'
        type: choice
        options:
          - dev
          - main
jobs:
  echo-inputs:
    name: Repo Workflow Debugging
    runs-on: ubuntu-latest
    steps:
      - name: Check Repo Vars
        run: |
          echo "*** Start 
          Check inputs in repo
          workflow ***"echo "Node Version:
           "Format: Check Required: 
          ${{ vars.IS_FORMAT_CHECK_REQUIRED }}"
           "Apply: Patches Required: ${{ vars.IS_APPLY_PATCHES_REQUIRED }}"
           "Unit Tests Required:echo
           "*** End - Check
           inputs in repo workflow ***" ci-test-only:
    if: ${{ github.event.inputs.workflowBranch == 'dev' }}
    uses: shardeum/github-automation/.github/workflows/reusable-node-ci.yml@dev
    permissions:
      issues: read
      contents: read
  ci:
    if: ${{ github.event.inputs.workflowBranch == 'main' || !github.event.inputs.workflowBranch }}
    uses: shardeum/github-automation/.github/workflows/reusable-node-ci.yml@main
    permissions:
      issues: read
      pull-requests: wread
      contents: read
